
package com.maogousoft.wuliuweb.service.credentials;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "idVerifyServicePortType", targetNamespace = "http://www.wqyx.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IdVerifyServicePortType {


    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @param in5
     * @param in6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://www.wqyx.com")
    @RequestWrapper(localName = "verifyService", targetNamespace = "http://www.wqyx.com", className = "com.jj.VerifyService")
    @ResponseWrapper(localName = "verifyServiceResponse", targetNamespace = "http://www.wqyx.com", className = "com.jj.VerifyServiceResponse")
    public String verifyService(
        @WebParam(name = "in0", targetNamespace = "http://www.wqyx.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://www.wqyx.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://www.wqyx.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://www.wqyx.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://www.wqyx.com")
        String in4,
        @WebParam(name = "in5", targetNamespace = "http://www.wqyx.com")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://www.wqyx.com")
        String in6);

}
