
package com.maogousoft.wuliuweb.service.credentials;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "idVerifyService", targetNamespace = "http://www.wqyx.com", wsdlLocation = "http://121.199.14.98/wqyxservice/services/idVerifyService?wsdl")
public class IdVerifyService
    extends Service
{

    private final static URL IDVERIFYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(IdVerifyService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = IdVerifyService.class.getResource(".");
            url = new URL(baseUrl, "http://121.199.14.98/wqyxservice/services/idVerifyService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://121.199.14.98/wqyxservice/services/idVerifyService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IDVERIFYSERVICE_WSDL_LOCATION = url;
    }

    public IdVerifyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdVerifyService() {
        super(IDVERIFYSERVICE_WSDL_LOCATION, new QName("http://www.wqyx.com", "idVerifyService"));
    }

    /**
     * 
     * @return
     *     returns IdVerifyServicePortType
     */
    @WebEndpoint(name = "idVerifyServiceHttpPort")
    public IdVerifyServicePortType getIdVerifyServiceHttpPort() {
        return super.getPort(new QName("http://www.wqyx.com", "idVerifyServiceHttpPort"), IdVerifyServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdVerifyServicePortType
     */
    @WebEndpoint(name = "idVerifyServiceHttpPort")
    public IdVerifyServicePortType getIdVerifyServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.wqyx.com", "idVerifyServiceHttpPort"), IdVerifyServicePortType.class, features);
    }

}
